#ifndef TASKDBCONNECTOR_GLOBAL_H
#define TASKDBCONNECTOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TASKDBCONNECTOR_LIBRARY)
#  define TASKDBCONNECTORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TASKDBCONNECTORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TASKDBCONNECTOR_GLOBAL_H
